In [136]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

In [137]:
print(tf.__version__)

2.16.1


In [138]:
x = np.array([[185.32, 12.69],
              [231.01, 14.41],
              [175.37, 11.72],
              [187.12, 14.13],
              [225.91, 12.1],
              [208.41, 14.18],
              [207.08, 14.03],
              [280.6,  14.23],
              [202.87, 12.25],
              [259.92, 11.87],
              [196.7,  13.54],
              [270.31,  14.6],
              [192.95, 15.2],
              [213.57, 14.28]
              ])

y = np.array([0,1,0,1,0,1,0,1,0,1,0,1,1,0])


y = y.reshape(-1, 1)


# print(x , y)

# Normalization

In [139]:
print(f"Max min temp pre Normalization {np.max(x[:,0])} {np.min(x[:,0])}")
print(f"Max min dura pre Normalization {np.max(x[:,1])} {np.min(x[:,1])}")

Max min temp pre Normalization 280.6 175.37
Max min dura pre Normalization 15.2 11.72


In [140]:
normalization = tf.keras.layers.Normalization(axis=-1)
normalization.adapt(x)
normalized_x = normalization(x)

In [141]:
print(f"original daat:- {x}")
print(f"\n normalized daat:- {normalized_x}")

original daat:- [[185.32  12.69]
 [231.01  14.41]
 [175.37  11.72]
 [187.12  14.13]
 [225.91  12.1 ]
 [208.41  14.18]
 [207.08  14.03]
 [280.6   14.23]
 [202.87  12.25]
 [259.92  11.87]
 [196.7   13.54]
 [270.31  14.6 ]
 [192.95  15.2 ]
 [213.57  14.28]]

 normalized daat:- [[-0.9995718  -0.74535406]
 [ 0.44484636  0.8059088 ]
 [-1.314126   -1.6201935 ]
 [-0.942668    0.5533779 ]
 [ 0.28361803 -1.2774725 ]
 [-0.26961735  0.59847295]
 [-0.3116633   0.4631879 ]
 [ 2.0125577   0.6435671 ]
 [-0.44475615 -1.1421883 ]
 [ 1.3587918  -1.4849093 ]
 [-0.6398111   0.02125862]
 [ 1.687255    0.9772697 ]
 [-0.7583615   1.5184073 ]
 [-0.10649183  0.6886621 ]]


In [142]:
tf.random.set_seed(0)
model = Sequential([
    tf.keras.Input(shape=(2,)),
    Dense(units = 3 , activation = "sigmoid" , name = "layer1"),
    Dense(units = 1 , activation = "sigmoid" , name = "layer2")
])

In [143]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ layer1 (Dense)                       │ (None, 3)                   │               9 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ layer2 (Dense)                       │ (None, 1)                   │               4 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 13 (52.00 B)

 Trainable params: 13 (52.00 B)

 Non-trainable params: 0 (0.00 B)

# Parameters count

- Layer1 parameters = 2 * 3 (w) + 1 * 3 (b) = 9
- Layer 2 parameters = 3 * 1 (w) + 1 * 1 (b) = 4
- Total parameters = 9 + 4 = 13

In [144]:
L1_parameters = 2*3 + 1*3 
L2_parameters = 3*1 + 1*1

Total_parameters = L1_parameters + L2_parameters

print(Total_parameters)

13


In [145]:
w1 , b1 = model.get_layer("layer1").get_weights()
w2 , b2 = model.get_layer("layer2").get_weights()

In [146]:
print(w1)
print("\n" , b1)
print("\n",w2)
print("\n",b2)

[[-0.02422154  0.513124   -0.98391974]
 [-0.8700067  -0.20420057 -0.7046393 ]]

 [0. 0. 0.]

 [[-0.38206148]
 [-0.62536186]
 [ 0.6427053 ]]

 [0.]


In [147]:
Xt = normalized_x
Yt = y

In [148]:
model.compile(
    loss = tf.keras.losses.BinaryCrossentropy(),
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.01),
)

model.fit(
    Xt,Yt,            
    epochs=10,
)

Epoch 1/10


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.7462
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.7425
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.7389
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.7353
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.7318
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.7284
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.7249
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.7216
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.7183
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.7151


# Updated weights

In [149]:
W1, b1 = model.get_layer("layer1").get_weights()
W2, b2 = model.get_layer("layer2").get_weights()
print("W1:\n", W1, "\nb1:", b1)
print("W2:\n", W2, "\nb2:", b2)

W1:
 [[-0.12451074  0.41360432 -0.8840551 ]
 [-0.9701767  -0.30342582 -0.6051253 ]] 
b1: [-0.09620284 -0.09588804  0.09831239]
W2:
 [[-0.48317137]
 [-0.5280576 ]
 [ 0.54282063]] 
b2: [0.09782391]


**The model has been trained . You can now make pridictions.**
*Recall, we have normalized the input features so we must normalize our test data as well*

In [150]:
x_test = np.array([[100, 59],
    [160, 19],
    [130, 16],
    [145, 11],
    [125, 21],
    [120, 11]])
x_test_normalized = normalization(x_test)

In [151]:
predicted_values = model.predict(x_test_normalized)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step


In [152]:
print(predicted_values)

[[0.52443635]
 [0.54064906]
 [0.5945878 ]
 [0.4908318 ]
 [0.5461    ]
 [0.50205123]]


In [153]:
y_hat = np.zeros_like(predicted_values)

for i in range(len(y_hat)):
    if(predicted_values[i] >= 0.5):
        y_hat[i] = 1
    else:
        y_hat[i] = 0
  

In [154]:
decision = y_hat
print(decision)

[[1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]]
